Remove Copy from FutharkContext
Erk-/genfut pull request #20
Opened 2020-07-26 12:21 UTC by Erk-

This is a breaking change that will make it possible to automatically drop the context. It also has some changes for the generated api.

2020-07-27 09:36 UTC, Erk- commented
Thinking about it a bit more, the Context should not implement Clone as it is going to be broken if another context gets dropped. Though this could be remidied by internally wrapping the context in a reference counter so it is first deallocated when there are no references left. This would also make other things easier I think.

2020-07-27 09:55 UTC, athas commented
Why does it need to implement Clone at all?

2020-07-27 11:09 UTC, Erk- commented
It does not need to, I just forgot to remove it when refactoring it.

2020-07-27 21:45 UTC, porcuquine commented
I have only had time to begin trying to integrate/test this change. After adding lifetimes to all my opaque pointers, I got hit by compiler errors flowing from that. This might require a lot of refactoring to address — enough so to be problematic from my perspective if true. I don't have time to fully investigate any further for now, but unless I eventually find this can be absorbed with relatively low impact, I would favor the status quo.

I see the value of automating freeing, but I already manage resource allocation so having to do it manually (which I never do, by design) isn't a big problem.

2020-10-15 16:32 UTC, dignifiedquire commented on src/static/static_context.rs
> +    fn from(ctx: FutharkContext) -> Self {
This should really be markes as `unsafe`. I understand the trait is neat, but it is very easy to missuse this.

2020-10-15 16:33 UTC, dignifiedquire commented on src/static/static_context.rs
> +            std::mem::transmute(self.context)
This looks risky at best, likely unsound to me. 

```rust
fn ptr_mut(&mut self) -> *mut bindings::futhark_context {}
fn ptr(&self) -> *const bindings::futhark_context {}
```

would be the correct way

2020-10-15 16:41 UTC, Erk- commented on src/static/static_context.rs
> +            std::mem::transmute(self.context)
At this point I am not sure if I will merge this pr, I have some other ideas that likely will work better. 

I think that you are right that it may be unsound if used in certain ways. Here it is used to get the *mut pointer from a `&self` which is only sound because Futhark have internal sync.

2020-10-15 16:44 UTC, porcuquine requested changes
I haven't been able to make this work downstream yet, so I'm blocking now as a reminder to all that it's not ready yet.

2020-10-15 16:46 UTC, Erk- commented
I will close this for now as I don't think it is the best way to solve the issue. (for more info see #15)

2020-10-15 16:46 UTC, closed without merging